
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 20 2025 00:17:32 EST (Feb 20 2025 05:17:32 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i, SE);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i, SE;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i, SE;
  wire [4:0] skew_addr_cntr_o;
  wire mc_rb_fuse_vld_q, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16;
  SDFFRHQX1 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_16), .SI (skew_addr_cntr_o[4]), .SE
       (1'b0), .Q (skew_addr_cntr_o[4]));
  SDFFRHQX1 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_14), .SI (skew_addr_cntr_o[3]), .SE
       (1'b0), .Q (skew_addr_cntr_o[3]));
  NOR2XL g424__2398(.A (n_13), .B (n_15), .Y (n_16));
  SDFFRHQX1 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_10), .SI (skew_addr_cntr_o[0]), .SE
       (1'b0), .Q (skew_addr_cntr_o[0]));
  SDFFRHQX1 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_9), .SI (skew_addr_cntr_o[1]), .SE
       (1'b0), .Q (skew_addr_cntr_o[1]));
  SDFFRHQX1 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_8), .SI (skew_addr_cntr_o[2]), .SE
       (1'b0), .Q (skew_addr_cntr_o[2]));
  XNOR2X1 g426__5107(.A (skew_addr_cntr_o[4]), .B (n_11), .Y (n_15));
  NOR2BX1 g427__6260(.AN (n_12), .B (n_13), .Y (n_14));
  ADDHX1 g428__4319(.A (skew_addr_cntr_o[3]), .B (n_6), .CO (n_11), .S
       (n_12));
  NOR2XL g432__8428(.A (skew_addr_cntr_o[0]), .B (n_13), .Y (n_10));
  NOR2BX1 g433__5526(.AN (n_2), .B (n_13), .Y (n_9));
  NOR2BX1 g434__6783(.AN (n_7), .B (n_13), .Y (n_8));
  AOI2BB1X1 g435__3680(.A0N (mc_rb_fuse_vld_q), .A1N
       (mc_rb_ef1_svld_i), .B0 (n_5), .Y (n_13));
  ADDHX1 g436__1617(.A (skew_addr_cntr_o[2]), .B (n_1), .CO (n_6), .S
       (n_7));
  MXI2XL g437__2802(.A (n_4), .B (n_3), .S0 (skew_addr_cntr_o[4]), .Y
       (n_5));
  NOR3X1 g438__1705(.A (skew_addr_cntr_o[0]), .B (skew_addr_cntr_o[1]),
       .C (n_3), .Y (n_4));
  ADDHX1 g439__5122(.A (skew_addr_cntr_o[1]), .B (skew_addr_cntr_o[0]),
       .CO (n_1), .S (n_2));
  SDFFRXL mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .SI (n_0), .SE
       (1'b0), .Q (n_0), .QN (mc_rb_fuse_vld_q));
  OR2X1 g441__8246(.A (skew_addr_cntr_o[2]), .B (skew_addr_cntr_o[3]),
       .Y (n_3));
endmodule

