
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 20 2025 00:17:31 EST (Feb 20 2025 05:17:31 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i, SE);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i, SE;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i, SE;
  wire [4:0] skew_addr_cntr_o;
  wire mc_rb_fuse_vld_q, n_19, n_70, n_110, n_112, n_115, n_116, n_117;
  wire n_118, n_119, n_120, n_125, n_126, n_135, n_136, n_137;
  wire n_138, n_139, n_140, n_141, n_142, n_143, n_144, n_145;
  wire n_146, n_147, n_148, n_149, n_150, n_151;
  not g4 (n_19, gctl_rclk_orst_n_i);
  nand g168 (n_112, skew_addr_cntr_o[1], skew_addr_cntr_o[0]);
  or g179 (n_110, n_112, wc);
  not gc (wc, skew_addr_cntr_o[2]);
  or g196 (n_118, wc0, n_110);
  not gc0 (wc0, skew_addr_cntr_o[3]);
  or g222 (n_70, n_137, wc1);
  not gc1 (wc1, n_138);
  nand g223 (n_144, n_118, skew_addr_cntr_o[4]);
  or g224 (n_145, n_118, skew_addr_cntr_o[4]);
  nand g225 (n_119, n_144, n_145);
  nand g226 (n_137, n_135, n_136);
  nand g227 (n_146, skew_addr_cntr_o[3], n_110);
  or g228 (n_147, skew_addr_cntr_o[3], n_110);
  nand g229 (n_115, n_146, n_147);
  or g230 (n_136, skew_addr_cntr_o[4], wc2);
  not gc2 (wc2, n_120);
  nand g231 (n_148, skew_addr_cntr_o[2], n_112);
  or g232 (n_149, skew_addr_cntr_o[2], n_112);
  nand g233 (n_117, n_148, n_149);
  or g234 (n_120, n_125, n_126);
  or g235 (n_135, n_126, wc3);
  not gc3 (wc3, skew_addr_cntr_o[4]);
  or g236 (n_138, wc4, mc_rb_ef1_svld_i);
  not gc4 (wc4, mc_rb_fuse_vld_q);
  or g237 (n_150, wc5, skew_addr_cntr_o[1]);
  not gc5 (wc5, skew_addr_cntr_o[0]);
  or g238 (n_151, skew_addr_cntr_o[0], wc6);
  not gc6 (wc6, skew_addr_cntr_o[1]);
  nand g239 (n_116, n_150, n_151);
  or g240 (n_125, skew_addr_cntr_o[1], skew_addr_cntr_o[0]);
  or g241 (n_126, skew_addr_cntr_o[2], skew_addr_cntr_o[3]);
  and g242 (n_139, n_116, n_70);
  and g243 (n_140, n_70, wc7);
  not gc7 (wc7, skew_addr_cntr_o[0]);
  and g244 (n_141, n_115, n_70);
  and g245 (n_142, n_117, n_70);
  and g246 (n_143, n_119, n_70);
  CDN_flop mc_rb_fuse_vld_q_reg(.clk (mc_rb_ef1_sclk_i), .d
       (mc_rb_fuse_vld_i), .sena (1'b1), .aclr (n_19), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (mc_rb_fuse_vld_q));
  CDN_flop \skew_addr_cntr_reg[0] (.clk (mc_rb_ef1_sclk_i), .d (n_140),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[0]));
  CDN_flop \skew_addr_cntr_reg[1] (.clk (mc_rb_ef1_sclk_i), .d (n_139),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[1]));
  CDN_flop \skew_addr_cntr_reg[2] (.clk (mc_rb_ef1_sclk_i), .d (n_142),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[2]));
  CDN_flop \skew_addr_cntr_reg[3] (.clk (mc_rb_ef1_sclk_i), .d (n_141),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[3]));
  CDN_flop \skew_addr_cntr_reg[4] (.clk (mc_rb_ef1_sclk_i), .d (n_143),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[4]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
