============================================================
  Generated by:           Genus(TM) Synthesis Solution 21.14-s082_1
  Generated on:           Feb 14 2025  03:57:23 pm
  Module:                 mcrb
  Operating conditions:   TypTyp_0.8V_25C 
  Interconnect mode:      global
  Area mode:              physical library
============================================================


Path 1: VIOLATED (-789 ps) Setup Check with Pin skew_addr_cntr_reg[2]/CK->D
          Group: clk
     Startpoint: (R) mc_rb_fuse_vld_q_reg/CK
          Clock: (R) clk
       Endpoint: (R) skew_addr_cntr_reg[2]/D
          Clock: (R) clk

                     Capture       Launch     
        Clock Edge:+    5000            0     
       Src Latency:+       0            0     
       Net Latency:+       0 (I)        0 (I) 
           Arrival:=    5000            0     
                                              
             Setup:-     588                  
       Uncertainty:-      50                  
     Required Time:=    4362                  
      Launch Clock:-       0                  
         Data Path:-    5152                  
             Slack:=    -789                  

#-------------------------------------------------------------------------------------------------
#      Timing Point       Flags    Arc   Edge   Cell     Fanout Load Trans Delay Arrival Instance 
#                                                               (fF)  (ps)  (ps)   (ps)  Location 
#-------------------------------------------------------------------------------------------------
  mc_rb_fuse_vld_q_reg/CK -       -      R     (arrival)      6    -    10     0       0    (-,-) 
  mc_rb_fuse_vld_q_reg/Q  -       CK->Q  R     DFFR_X2        1  9.2  1183  2199    2199    (-,-) 
  g22/ZN                  -       A1->ZN F     NAND2_X4       1  9.5   434   474    2673    (-,-) 
  g21/ZN                  -       A3->ZN R     NAND3_X4       1 12.5  1037   675    3348    (-,-) 
  g11168__11359/ZN        -       A1->ZN F     NAND3_X4       1 11.0   539   524    3872    (-,-) 
  g11167/ZN               -       A->ZN  R     INV_X32        5 26.3   530   460    4332    (-,-) 
  g11163__8428/ZN         -       A2->ZN R     AND2_X2        1  9.4  1201   820    5151    (-,-) 
  skew_addr_cntr_reg[2]/D <<<     -      R     DFFR_X2        1    -     -     0    5152    (-,-) 
#-------------------------------------------------------------------------------------------------

