
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 10 2025 23:47:26 EST (Feb 11 2025 04:47:26 UTC)

// Verification Directory fv/s298 

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  input GND, VDD, CK, G0, G1, G2;
  output G117, G118, G132, G133, G66, G67;
  wire GND, VDD, CK, G0, G1, G2;
  wire G117, G118, G132, G133, G66, G67;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, n_0, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_30, n_31;
  wire n_32, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_47, n_48;
  DFFHQX1 DFF_10_q_reg(.CK (CK), .D (n_45), .Q (G132));
  DFFTRX1 DFF_5_q_reg(.CK (CK), .D (n_40), .RN (n_44), .Q (G15), .QN
       (UNCONNECTED));
  OAI21XL g1153__2398(.A0 (n_39), .A1 (G10), .B0 (n_30), .Y (n_45));
  DFFHQX1 DFF_6_q_reg(.CK (CK), .D (n_42), .Q (G66));
  DFFHQX1 DFF_9_q_reg(.CK (CK), .D (n_43), .Q (G118));
  DFFTRX1 DFF_4_q_reg(.CK (CK), .D (n_37), .RN (n_44), .Q (G14), .QN
       (n_0));
  NAND2X1 g1157__5107(.A (n_36), .B (n_41), .Y (n_43));
  OAI2BB1X1 g1158__6260(.A0N (G66), .A1N (n_35), .B0 (n_41), .Y (n_42));
  INVX1 g1159(.A (n_39), .Y (n_40));
  OAI2BB2X1 g1154__4319(.A0N (n_6), .A1N (G13), .B0 (n_31), .B1 (G0),
       .Y (n_38));
  AOI21X1 g1162__8428(.A0 (n_47), .A1 (G15), .B0 (n_16), .Y (n_39));
  DFFHQX1 DFF_7_q_reg(.CK (CK), .D (n_34), .Q (G67));
  XNOR2X1 g1167__5526(.A (n_23), .B (G14), .Y (n_37));
  AOI22X1 g1169__6783(.A0 (n_22), .A1 (n_32), .B0 (n_4), .B1 (n_17), .Y
       (n_41));
  DFFHQX1 DFF_8_q_reg(.CK (CK), .D (n_28), .Q (G117));
  AOI211X1 g1165__3680(.A0 (n_35), .A1 (G118), .B0 (n_48), .C0 (n_18),
       .Y (n_36));
  OAI211X1 g1166__1617(.A0 (n_27), .A1 (G11), .B0 (n_19), .C0 (n_26),
       .Y (n_34));
  DFFHQX1 DFF_11_q_reg(.CK (CK), .D (n_21), .Q (G133));
  AOI22X1 g1168__1705(.A0 (n_11), .A1 (n_13), .B0 (n_24), .B1 (G11), .Y
       (n_31));
  AOI21X1 g1170__5122(.A0 (n_35), .A1 (G132), .B0 (n_48), .Y (n_30));
  NAND3X1 g1174__8246(.A (n_20), .B (n_27), .C (n_26), .Y (n_28));
  OAI31X1 g1175__7098(.A0 (n_8), .A1 (n_24), .A2 (G0), .B0 (n_7), .Y
       (n_25));
  AND2X2 g1180__6131(.A (n_9), .B (G23), .Y (n_23));
  OAI21XL g1182__1881(.A0 (n_3), .A1 (G15), .B0 (n_14), .Y (n_22));
  OAI2BB1X1 g1173__5115(.A0N (G133), .A1N (n_35), .B0 (n_12), .Y
       (n_21));
  EDFFTRX1 DFF_2_q_reg(.CK (CK), .D (G12), .E (n_10), .RN (n_44), .Q
       (n_13), .QN (G12));
  NAND2X1 g1177__7482(.A (n_35), .B (G117), .Y (n_20));
  NAND2X1 g1178__4733(.A (n_35), .B (G67), .Y (n_19));
  AOI2BB1XL g1179__6161(.A0N (n_17), .A1N (G15), .B0 (G10), .Y (n_18));
  NOR4BX1 g1181__9315(.AN (n_24), .B (G22), .C (G14), .D (G11), .Y
       (n_16));
  NAND3X1 g1183__2883(.A (n_32), .B (n_5), .C (n_13), .Y (n_12));
  MX2X1 g1184__2346(.S0 (G13), .B (n_2), .A (n_10), .Y (n_11));
  NAND2X1 g1189__1666(.A (n_24), .B (G22), .Y (n_14));
  NAND2BX1 g1192__7410(.AN (n_8), .B (n_24), .Y (n_9));
  EDFFTRX1 DFF_13_q_reg(.CK (CK), .D (G23), .E (G1), .RN (n_44), .Q
       (UNCONNECTED0), .QN (G23));
  EDFFTRX1 DFF_12_q_reg(.CK (CK), .D (G22), .E (G2), .RN (n_44), .Q
       (UNCONNECTED1), .QN (G22));
  NAND2X1 g1187__6417(.A (G11), .B (n_6), .Y (n_7));
  NAND3X1 g1193__5477(.A (n_5), .B (G12), .C (G11), .Y (n_26));
  NAND2BX1 g1188__2398(.AN (G14), .B (n_5), .Y (n_27));
  AOI2BB1XL g1191__5107(.A0N (G22), .A1N (n_13), .B0 (G15), .Y (n_4));
  DFFHQX1 DFF_0_q_reg(.CK (CK), .D (n_6), .Q (G10));
  AOI211X1 g1194__6260(.A0 (n_3), .A1 (G12), .B0 (n_0), .C0 (G15), .Y
       (n_35));
  NAND2X1 g1199__4319(.A (n_2), .B (G10), .Y (n_8));
  NOR2X1 g1196__8428(.A (n_3), .B (G14), .Y (n_17));
  NOR2X1 g1197__5526(.A (n_2), .B (G14), .Y (n_32));
  NOR2X1 g1202__6783(.A (n_3), .B (n_13), .Y (n_24));
  AND2X2 g1201__3680(.A (G11), .B (G10), .Y (n_10));
  NOR2X1 g1200__1617(.A (G10), .B (G0), .Y (n_6));
  NOR2X1 g1198__2802(.A (G15), .B (G13), .Y (n_5));
  INVXL g1203(.A (G0), .Y (n_44));
  DFFX1 DFF_1_q_reg(.CK (CK), .D (n_25), .Q (G11), .QN (n_2));
  DFFX1 DFF_3_q_reg(.CK (CK), .D (n_38), .Q (G13), .QN (n_3));
  NAND2BX1 g2(.AN (n_14), .B (n_32), .Y (n_47));
  NOR4BBX1 g1226(.AN (G14), .BN (n_5), .C (G11), .D (n_13), .Y (n_48));
endmodule

