
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 20 2025 00:20:22 EST (Feb 20 2025 05:20:22 UTC)

// Verification Directory fv/s298 

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67,
     SE, scan_in, scan_out);
  input GND, VDD, CK, G0, G1, G2, SE, scan_in;
  output G117, G118, G132, G133, G66, G67, scan_out;
  wire GND, VDD, CK, G0, G1, G2, SE, scan_in;
  wire G117, G118, G132, G133, G66, G67, scan_out;
  wire G10, G11, G12, G13, G14, G15, G22, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51;
  SDFFQX1 DFF_10_q_reg(.CK (CK), .D (n_50), .SI (G118), .SE (SE), .Q
       (G132));
  SDFFQX1 DFF_9_q_reg(.CK (CK), .D (n_51), .SI (G117), .SE (SE), .Q
       (G118));
  SDFFQXL DFF_5_q_reg(.CK (CK), .D (n_48), .SI (G14), .SE (SE), .Q
       (G15));
  SDFFQX2 DFF_3_q_reg(.CK (CK), .D (n_46), .SI (G12), .SE (SE), .Q
       (G13));
  SDFFQX1 DFF_6_q_reg(.CK (CK), .D (n_44), .SI (G15), .SE (SE), .Q
       (G66));
  SDFFQX1 DFF_8_q_reg(.CK (CK), .D (n_40), .SI (G67), .SE (SE), .Q
       (G117));
  SDFFQX1 DFF_7_q_reg(.CK (CK), .D (n_41), .SI (G66), .SE (SE), .Q
       (G67));
  SDFFQX1 DFF_11_q_reg(.CK (CK), .D (n_35), .SI (G132), .SE (SE), .Q
       (G133));
  NAND2BX1 g1191__2398(.AN (n_42), .B (n_45), .Y (n_51));
  OAI211X1 g1185__5107(.A0 (G10), .A1 (n_47), .B0 (n_37), .C0 (n_29),
       .Y (n_50));
  NOR2X1 g1190__6260(.A (n_39), .B (G0), .Y (n_49));
  NOR2XL g1192__4319(.A (G0), .B (n_47), .Y (n_48));
  SDFFQX2 DFF_2_q_reg(.CK (CK), .D (n_26), .SI (G11), .SE (SE), .Q
       (G12));
  SDFFQX2 DFF_1_q_reg(.CK (CK), .D (n_25), .SI (G10), .SE (SE), .Q
       (G11));
  OAI22X1 g1184__8428(.A0 (n_31), .A1 (G0), .B0 (n_6), .B1 (n_23), .Y
       (n_46));
  AOI21X1 g1201__5526(.A0 (G118), .A1 (n_43), .B0 (n_38), .Y (n_45));
  AO21X1 g1194__6783(.A0 (G66), .A1 (n_43), .B0 (n_42), .Y (n_44));
  OAI211X1 g1198__3680(.A0 (G11), .A1 (n_33), .B0 (n_32), .C0 (n_30),
       .Y (n_41));
  OAI2BB1X1 g1199__1617(.A0N (G117), .A1N (n_43), .B0 (n_34), .Y
       (n_40));
  CLKXOR2X1 g1200__2802(.A (G14), .B (n_28), .Y (n_39));
  AOI21X1 g1202__1705(.A0 (G15), .A1 (n_36), .B0 (n_19), .Y (n_47));
  OAI21X1 g1209__5122(.A0 (G10), .A1 (n_13), .B0 (n_37), .Y (n_38));
  OAI31X1 g1210__8246(.A0 (G15), .A1 (n_12), .A2 (n_4), .B0 (n_36), .Y
       (n_42));
  OAI2BB1X1 g1207__7098(.A0N (G133), .A1N (n_43), .B0 (n_27), .Y
       (n_35));
  SDFFQX1 DFF_13_q_reg(.CK (CK), .D (n_17), .SI (G22), .SE (SE), .Q
       (scan_out));
  SDFFQX1 DFF_12_q_reg(.CK (CK), .D (n_16), .SI (G133), .SE (SE), .Q
       (G22));
  AND2X1 g1203__6131(.A (n_33), .B (n_32), .Y (n_34));
  AOI21X1 g1193__1881(.A0 (G12), .A1 (n_18), .B0 (n_21), .Y (n_31));
  NAND2XL g1211__5115(.A (G67), .B (n_43), .Y (n_30));
  NAND2XL g1212__7482(.A (G132), .B (n_43), .Y (n_29));
  AOI21X1 g1215__4733(.A0 (n_24), .A1 (n_8), .B0 (scan_out), .Y (n_28));
  SDFFQXL DFF_0_q_reg(.CK (CK), .D (n_1), .SI (scan_in), .SE (SE), .Q
       (G10));
  NAND3X1 g1217__6161(.A (G12), .B (G11), .C (n_11), .Y (n_27));
  NOR2XL g1204__9315(.A (n_15), .B (G0), .Y (n_26));
  OAI32X1 g1208__9945(.A0 (n_24), .A1 (n_7), .A2 (G0), .B0 (n_22), .B1
       (n_23), .Y (n_25));
  NAND3X1 g1221__2883(.A (G14), .B (n_22), .C (n_20), .Y (n_37));
  NAND2XL g1222__2346(.A (n_0), .B (n_21), .Y (n_36));
  NAND2XL g1216__1666(.A (G11), .B (n_20), .Y (n_32));
  AND4X1 g1219__7410(.A (G22), .B (n_22), .C (n_10), .D (n_24), .Y
       (n_19));
  MXI2XL g1218__6417(.A (n_14), .B (G11), .S0 (G13), .Y (n_18));
  NOR2XL g1214__5477(.A (G0), .B (n_3), .Y (n_17));
  NOR2XL g1213__2398(.A (G0), .B (n_2), .Y (n_16));
  CLKXOR2X1 g1220__5107(.A (G12), .B (n_14), .Y (n_15));
  NOR2BX1 g1223__6260(.AN (n_12), .B (G15), .Y (n_13));
  AND2X1 g1225__4319(.A (G11), .B (n_24), .Y (n_21));
  CLKINVX1 g1227(.A (n_11), .Y (n_33));
  NOR3X2 g1232__8428(.A (G15), .B (n_10), .C (n_9), .Y (n_43));
  CLKAND2X2 g1224__5526(.A (n_9), .B (n_5), .Y (n_20));
  CLKINVX1 g1237(.A (n_7), .Y (n_8));
  AND3X1 g1231__6783(.A (n_6), .B (n_10), .C (n_5), .Y (n_11));
  NOR3BX1 g1228__3680(.AN (G22), .B (G12), .C (G11), .Y (n_4));
  XNOR2X1 g1229__1617(.A (scan_out), .B (G1), .Y (n_3));
  XNOR2X1 g1230__2802(.A (G22), .B (G2), .Y (n_2));
  CLKINVX1 g1233(.A (n_23), .Y (n_1));
  NAND2XL g1240__1705(.A (G10), .B (n_22), .Y (n_7));
  NAND2XL g1239__5122(.A (G13), .B (n_10), .Y (n_12));
  NOR2X2 g1236__8246(.A (G12), .B (n_6), .Y (n_24));
  NOR2XL g1234__7098(.A (G12), .B (G13), .Y (n_9));
  OR2X1 g1235__6131(.A (G10), .B (G0), .Y (n_23));
  NOR2XL g1238__1881(.A (G22), .B (G14), .Y (n_0));
  NAND2XL g1241__5115(.A (G10), .B (G11), .Y (n_14));
  CLKINVX1 g1244(.A (G13), .Y (n_6));
  CLKINVX1 g1245(.A (G11), .Y (n_22));
  CLKINVX1 g1242(.A (G15), .Y (n_5));
  CLKINVX1 g1243(.A (G14), .Y (n_10));
  SDFFQX1 DFF_4_q_reg(.CK (CK), .D (n_49), .SI (G13), .SE (SE), .Q
       (G14));
endmodule

