
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 14 2025 15:53:42 IST (Feb 14 2025 10:23:42 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire [4:0] skew_addr_cntr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, mc_rb_fuse_vld_q, n_0;
  wire n_2, n_4, n_5, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  DFFR_X2 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_49), .Q (UNCONNECTED), .QN
       (skew_addr_cntr[1]));
  DFFR_X1 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_51), .Q (UNCONNECTED0), .QN
       (skew_addr_cntr[0]));
  DFFR_X1 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_48), .Q (UNCONNECTED1), .QN
       (skew_addr_cntr[3]));
  DFFR_X1 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_52), .Q (UNCONNECTED2), .QN
       (skew_addr_cntr[4]));
  DFFR_X2 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_47), .Q (UNCONNECTED3), .QN
       (skew_addr_cntr[2]));
  AND2_X2 g11164__2398(.A1 (n_50), .A2 (n_45), .ZN (n_52));
  AND2_X2 g11165__5107(.A1 (n_50), .A2 (n_35), .ZN (n_51));
  AND2_X2 g11162__6260(.A1 (n_50), .A2 (n_36), .ZN (n_49));
  AND2_X2 g11166__4319(.A1 (n_50), .A2 (n_44), .ZN (n_48));
  AND2_X2 g11163__8428(.A1 (n_50), .A2 (n_43), .ZN (n_47));
  INV_X32 g11167(.A (n_46), .ZN (n_50));
  NAND3_X4 g11168__5526(.A1 (n_42), .A2 (n_37), .A3 (n_38), .ZN (n_46));
  MUX2_X2 g11169__6783(.A (n_18), .B (n_19), .S (n_40), .Z (n_45));
  MUX2_X1 g11170__3680(.A (n_21), .B (n_20), .S (n_41), .Z (n_44));
  MUX2_X2 g11174__1617(.A (n_30), .B (n_29), .S (n_34), .Z (n_43));
  NAND3_X4 g11173__2802(.A1 (n_5), .A2 (n_33), .A3 (n_22), .ZN (n_42));
  NAND2_X4 g11176__1705(.A1 (n_39), .A2 (n_24), .ZN (n_41));
  NAND2_X4 g11177__5122(.A1 (n_31), .A2 (n_39), .ZN (n_40));
  NAND4_X4 g11171__8246(.A1 (mc_rb_ef1_svld_i), .A2 (n_7), .A3 (n_28),
       .A4 (n_23), .ZN (n_38));
  NAND2_X4 g11172__7098(.A1 (n_27), .A2 (n_32), .ZN (n_37));
  XOR2_X2 g11180__6131(.A (n_35), .B (n_6), .Z (n_36));
  INV_X8 g11187(.A (n_39), .ZN (n_34));
  NAND2_X4 g11175__1881(.A1 (n_14), .A2 (n_0), .ZN (n_33));
  INV_X16 g11188(.A (n_17), .ZN (n_39));
  AND3_X2 g11178__5115(.A1 (n_11), .A2 (mc_rb_fuse_vld_q), .A3 (n_9),
       .ZN (n_32));
  INV_X8 g11185(.A (n_26), .ZN (n_31));
  INV_X8 g11210(.A (n_29), .ZN (n_30));
  INV_X8 g11181(.A (n_13), .ZN (n_28));
  AND3_X2 g11179__7482(.A1 (n_8), .A2 (n_2), .A3 (n_12), .ZN (n_27));
  NAND2_X4 g11189__4733(.A1 (skew_addr_cntr_o[3]), .A2 (n_10), .ZN
       (n_26));
  BUF_X8 g11211(.A (n_24), .Z (n_29));
  INV_X16 g11186(.A (n_22), .ZN (n_23));
  INV_X8 g11202(.A (n_20), .ZN (n_21));
  INV_X8 g11193(.A (n_18), .ZN (n_19));
  NAND2_X4 g11191__6161(.A1 (skew_addr_cntr_o[1]), .A2
       (skew_addr_cntr_o[0]), .ZN (n_17));
  INV_X8 g11182(.A (mc_rb_fuse_vld_q), .ZN (n_14));
  NAND2_X4 g11183__9315(.A1 (n_12), .A2 (n_11), .ZN (n_13));
  BUF_X16 g11212(.A (n_10), .Z (n_24));
  NAND2_X4 g11190__9945(.A1 (n_8), .A2 (n_9), .ZN (n_22));
  BUF_X8 g11198(.A (n_6), .Z (n_7));
  INV_X16 g11195(.A (n_4), .ZN (n_5));
  BUF_X8 g11203(.A (skew_addr_cntr_o[3]), .Z (n_20));
  INV_X16 g11207(.A (skew_addr_cntr_o[0]), .ZN (n_35));
  BUF_X8 g11194(.A (n_4), .Z (n_18));
  INV_X2 g11214(.A (n_8), .ZN (skew_addr_cntr_o[2]));
  BUF_X32 g11199(.A (n_2), .Z (n_6));
  INV_X32 g11213(.A (n_8), .ZN (n_10));
  INV_X32 g11208(.A (n_11), .ZN (skew_addr_cntr_o[0]));
  INV_X2 g11192(.A (n_12), .ZN (skew_addr_cntr_o[4]));
  BUF_X16 g11196(.A (n_12), .Z (n_4));
  INV_X16 g11200(.A (n_2), .ZN (skew_addr_cntr_o[1]));
  DFFR_X2 mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .Q (UNCONNECTED4),
       .QN (mc_rb_fuse_vld_q));
  INV_X16 g11204(.A (n_9), .ZN (skew_addr_cntr_o[3]));
  BUF_X16 g11209(.A (skew_addr_cntr[0]), .Z (n_11));
  BUF_X16 g11205(.A (skew_addr_cntr[3]), .Z (n_9));
  BUF_X16 g11197(.A (skew_addr_cntr[4]), .Z (n_12));
  INV_X8 g11206(.A (mc_rb_ef1_svld_i), .ZN (n_0));
  BUF_X32 g11201(.A (skew_addr_cntr[1]), .Z (n_2));
  BUF_X16 g11215(.A (skew_addr_cntr[2]), .Z (n_8));
endmodule

