
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 14 2025 15:57:01 IST (Feb 14 2025 10:27:01 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire [4:0] skew_addr_cntr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, mc_rb_fuse_vld_q, n_0, n_14;
  wire n_21, n_34, n_41, n_43, n_44, n_47, n_48, n_49;
  wire n_50, n_51, n_179, n_181, n_182, n_184, n_185, n_206;
  wire n_223, n_260, n_263, n_264, n_265, n_266, n_267, n_268;
  wire n_269, n_271, n_272, n_273, n_274, n_278, n_279, n_281;
  wire n_284, n_312, n_314, n_315, n_320, n_322, n_391, n_392;
  wire n_393, n_394, n_395;
  DFFR_X2 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_49), .Q (UNCONNECTED), .QN
       (skew_addr_cntr[1]));
  DFFR_X1 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_51), .Q (UNCONNECTED0), .QN
       (skew_addr_cntr[0]));
  DFFR_X1 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_48), .Q (UNCONNECTED1), .QN
       (skew_addr_cntr[3]));
  DFFR_X1 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_279), .Q (UNCONNECTED2), .QN
       (skew_addr_cntr[4]));
  DFFR_X2 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_47), .Q (UNCONNECTED3), .QN
       (skew_addr_cntr[2]));
  AND2_X2 g11165__5107(.A1 (n_181), .A2 (n_50), .ZN (n_51));
  AND2_X2 g11162__6260(.A1 (n_185), .A2 (n_50), .ZN (n_49));
  AND2_X2 g11166__4319(.A1 (n_44), .A2 (n_50), .ZN (n_48));
  AND2_X2 g11163__8428(.A1 (n_43), .A2 (n_50), .ZN (n_47));
  INV_X32 g11167(.A (n_284), .ZN (n_50));
  MUX2_X2 g11170__3680(.A (n_21), .B (skew_addr_cntr_o[3]), .S (n_41),
       .Z (n_44));
  MUX2_X2 g11174__1617(.A (n_320), .B (skew_addr_cntr_o[2]), .S (n_34),
       .Z (n_43));
  NAND2_X4 g11176__1705(.A1 (n_179), .A2 (skew_addr_cntr_o[2]), .ZN
       (n_41));
  INV_X8 g11187(.A (n_179), .ZN (n_34));
  INV_X2 g11202(.A (skew_addr_cntr_o[3]), .ZN (n_21));
  DFFR_X2 mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .Q (n_14), .QN
       (mc_rb_fuse_vld_q));
  INV_X2 g11206(.A (mc_rb_ef1_svld_i), .ZN (n_0));
  INV_X32 g32(.A (n_223), .ZN (n_179));
  MUX2_X2 g17(.A (n_181), .B (n_182), .S (n_184), .Z (n_185));
  BUF_X16 g19(.A (n_269), .Z (n_181));
  INV_X8 g18(.A (n_181), .ZN (n_182));
  NAND4_X4 g30(.A1 (skew_addr_cntr_o[2]), .A2 (skew_addr_cntr_o[0]),
       .A3 (skew_addr_cntr_o[3]), .A4 (skew_addr_cntr_o[1]), .ZN
       (n_206));
  INV_X16 g11323(.A (n_271), .ZN (skew_addr_cntr_o[3]));
  NAND2_X4 g9(.A1 (skew_addr_cntr_o[1]), .A2 (skew_addr_cntr_o[0]), .ZN
       (n_223));
  INV_X32 fopt15(.A (n_260), .ZN (skew_addr_cntr_o[1]));
  INV_X32 fopt11333(.A (n_269), .ZN (skew_addr_cntr_o[0]));
  NAND4_X4 g11346(.A1 (n_184), .A2 (n_263), .A3 (n_265), .A4 (n_267),
       .ZN (n_268));
  BUF_X16 fopt11347(.A (n_260), .Z (n_184));
  BUF_X32 fopt53(.A (skew_addr_cntr[1]), .Z (n_260));
  BUF_X16 g51(.A (n_269), .Z (n_263));
  INV_X16 g11349(.A (n_264), .ZN (n_265));
  NAND2_X4 g11350(.A1 (n_314), .A2 (mc_rb_ef1_svld_i), .ZN (n_264));
  INV_X16 g11351(.A (n_266), .ZN (n_267));
  NAND2_X4 g11352(.A1 (n_315), .A2 (n_271), .ZN (n_266));
  BUF_X32 g1(.A (skew_addr_cntr[0]), .Z (n_269));
  BUF_X16 g11354(.A (n_271), .Z (n_272));
  BUF_X16 g11355(.A (skew_addr_cntr[3]), .Z (n_271));
  INV_X16 g11356(.A (n_273), .ZN (n_274));
  NAND2_X4 g11357(.A1 (n_314), .A2 (mc_rb_fuse_vld_q), .ZN (n_273));
  AND2_X2 g34(.A1 (n_278), .A2 (n_50), .ZN (n_279));
  MUX2_X1 g35(.A (n_312), .B (skew_addr_cntr_o[4]), .S (n_206), .Z
       (n_278));
  NAND3_X4 g11168__11359(.A1 (n_395), .A2 (n_393), .A3 (n_268), .ZN
       (n_284));
  NAND2_X4 g11362(.A1 (n_315), .A2 (n_271), .ZN (n_281));
  INV_X32 fopt11390(.A (n_312), .ZN (skew_addr_cntr_o[4]));
  BUF_X16 fopt3(.A (n_314), .Z (n_312));
  BUF_X16 fopt4(.A (skew_addr_cntr[4]), .Z (n_314));
  INV_X2 fopt7(.A (skew_addr_cntr_o[2]), .ZN (n_320));
  INV_X32 fopt8(.A (n_315), .ZN (skew_addr_cntr_o[2]));
  INV_X32 fopt9(.A (n_322), .ZN (n_315));
  INV_X32 fopt10(.A (skew_addr_cntr[2]), .ZN (n_322));
  NAND4_X4 g40(.A1 (n_272), .A2 (n_263), .A3 (n_274), .A4 (n_392), .ZN
       (n_393));
  INV_X32 g41(.A (n_391), .ZN (n_392));
  NAND2_X4 g42(.A1 (n_260), .A2 (n_315), .ZN (n_391));
  NAND3_X4 g21(.A1 (n_281), .A2 (skew_addr_cntr_o[4]), .A3 (n_394), .ZN
       (n_395));
  NAND2_X4 g22(.A1 (n_14), .A2 (n_0), .ZN (n_394));
endmodule

