
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 13 2025 12:16:13 IST (Feb 13 2025 06:46:13 UTC)

// Verification Directory fv/s298 

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67,
     scan_in, scan_out);
  input GND, VDD, CK, G0, G1, G2, scan_in;
  output G117, G118, G132, G133, G66, G67, scan_out;
  wire GND, VDD, CK, G0, G1, G2, scan_in;
  wire G117, G118, G132, G133, G66, G67, scan_out;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_48;
  wire n_49, n_50, n_52, n_54;
  SDFFQX1 DFF_10_q_reg(.CK (CK), .D (n_52), .SI (G132), .SE (1'b0), .Q
       (G132));
  SDFFQX1 DFF_6_q_reg(.CK (CK), .D (n_54), .SI (G66), .SE (1'b0), .Q
       (G66));
  SDFFQX1 DFF_9_q_reg(.CK (CK), .D (n_48), .SI (G118), .SE (1'b0), .Q
       (G118));
  SDFFQX2 DFF_5_q_reg(.CK (CK), .D (n_50), .SI (G15), .SE (1'b0), .Q
       (G15));
  SDFFQX2 DFF_3_q_reg(.CK (CK), .D (n_44), .SI (G13), .SE (1'b0), .Q
       (G13));
  SDFFQX2 DFF_4_q_reg(.CK (CK), .D (n_45), .SI (G14), .SE (1'b0), .Q
       (G14));
  OAI211X1 g1130__2398(.A0 (G10), .A1 (n_49), .B0 (n_38), .C0 (n_22),
       .Y (n_52));
  SDFFQX1 DFF_7_q_reg(.CK (CK), .D (n_41), .SI (G67), .SE (1'b0), .Q
       (G67));
  SDFFQX1 DFF_8_q_reg(.CK (CK), .D (n_36), .SI (G117), .SE (1'b0), .Q
       (G117));
  NOR2XL g1134__6260(.A (n_49), .B (G0), .Y (n_50));
  NAND2BX1 g1135__4319(.AN (n_46), .B (n_43), .Y (n_48));
  SDFFQX1 DFF_11_q_reg(.CK (CK), .D (n_33), .SI (G133), .SE (1'b0), .Q
       (G133));
  SDFFQX2 DFF_2_q_reg(.CK (CK), .D (n_24), .SI (G12), .SE (1'b0), .Q
       (G12));
  SDFFQX2 DFF_1_q_reg(.CK (CK), .D (n_32), .SI (G11), .SE (1'b0), .Q
       (G11));
  NOR2XL g1132__8428(.A (n_40), .B (G0), .Y (n_45));
  OAI22X1 g1129__5526(.A0 (n_37), .A1 (G0), .B0 (n_26), .B1 (n_30), .Y
       (n_44));
  AOI21X1 g1139__6783(.A0 (G15), .A1 (n_29), .B0 (n_19), .Y (n_49));
  AOI21X1 g1144__3680(.A0 (G118), .A1 (n_42), .B0 (n_39), .Y (n_43));
  OAI32X1 g1147__1617(.A0 (G15), .A1 (n_2), .A2 (n_10), .B0 (n_28), .B1
       (n_27), .Y (n_46));
  SDFFQX1 DFF_13_q_reg(.CK (CK), .D (n_16), .SI (G23), .SE (1'b0), .Q
       (G23));
  SDFFQX1 DFF_12_q_reg(.CK (CK), .D (n_15), .SI (G22), .SE (1'b0), .Q
       (G22));
  OAI211X1 g1143__2802(.A0 (G11), .A1 (n_35), .B0 (n_34), .C0 (n_23),
       .Y (n_41));
  CLKXOR2X1 g1145__1705(.A (G14), .B (n_21), .Y (n_40));
  OAI21X1 g1153__5122(.A0 (G10), .A1 (n_11), .B0 (n_38), .Y (n_39));
  AOI22X1 g1146__8246(.A0 (G12), .A1 (n_14), .B0 (G11), .B1 (n_31), .Y
       (n_37));
  OAI211X1 g1151__7098(.A0 (n_0), .A1 (n_9), .B0 (n_35), .C0 (n_34), .Y
       (n_36));
  OAI2BB1X1 g1152__6131(.A0N (G133), .A1N (n_42), .B0 (n_17), .Y
       (n_33));
  OAI32X1 g1154__1881(.A0 (n_31), .A1 (n_20), .A2 (G0), .B0 (n_8), .B1
       (n_30), .Y (n_32));
  SDFFQXL DFF_0_q_reg(.CK (CK), .D (n_5), .SI (G10), .SE (1'b0), .Q
       (G10));
  NAND2BX1 g1159__5115(.AN (n_28), .B (n_25), .Y (n_29));
  AOI2BB1X1 g1161__7482(.A0N (n_26), .A1N (G15), .B0 (n_25), .Y (n_27));
  NOR2XL g1148__4733(.A (n_13), .B (G0), .Y (n_24));
  NAND2X1 g1155__6161(.A (G67), .B (n_42), .Y (n_23));
  NAND2X1 g1156__9315(.A (G132), .B (n_42), .Y (n_22));
  AOI2BB1X1 g1160__9945(.A0N (n_18), .A1N (n_20), .B0 (G23), .Y (n_21));
  NOR4BX1 g1164__2883(.AN (G22), .B (G11), .C (G14), .D (n_18), .Y
       (n_19));
  NAND3BX1 g1162__2346(.AN (n_28), .B (G12), .C (n_7), .Y (n_17));
  NOR2XL g1158__1666(.A (G0), .B (n_4), .Y (n_16));
  NOR2XL g1157__7410(.A (G0), .B (n_3), .Y (n_15));
  MXI2XL g1163__6417(.A (n_12), .B (G11), .S0 (G13), .Y (n_14));
  CLKXOR2X1 g1165__5477(.A (G12), .B (n_12), .Y (n_13));
  NOR2BX1 g1167__2398(.AN (n_10), .B (G15), .Y (n_11));
  CLKINVX1 g1171(.A (n_42), .Y (n_9));
  NAND4XL g1166__5107(.A (n_6), .B (G14), .C (n_8), .D (n_7), .Y
       (n_38));
  NOR2X1 g1168__6260(.A (G22), .B (n_18), .Y (n_25));
  NAND3X1 g1174__4319(.A (G11), .B (n_6), .C (n_7), .Y (n_34));
  NAND2BX1 g1169__8428(.AN (G14), .B (n_7), .Y (n_35));
  CLKINVX1 g1181(.A (n_18), .Y (n_31));
  AOI211X1 g1175__5526(.A0 (n_6), .A1 (n_26), .B0 (G15), .C0 (n_1), .Y
       (n_42));
  CLKINVX1 g1176(.A (n_30), .Y (n_5));
  XNOR2X1 g1173__6783(.A (G23), .B (G1), .Y (n_4));
  XNOR2X1 g1172__3680(.A (G22), .B (G2), .Y (n_3));
  AND2X1 g1177__1617(.A (n_6), .B (G22), .Y (n_2));
  NAND2XL g1182__2802(.A (G13), .B (n_1), .Y (n_10));
  NAND2XL g1178__1705(.A (G10), .B (n_8), .Y (n_20));
  OR2X1 g1180__5122(.A (G14), .B (n_8), .Y (n_28));
  NAND2X1 g1185__8246(.A (G13), .B (n_6), .Y (n_18));
  OR2X1 g1179__7098(.A (G10), .B (G0), .Y (n_30));
  NAND2XL g1183__6131(.A (G10), .B (G11), .Y (n_12));
  NOR2X2 g1184__1881(.A (G13), .B (G15), .Y (n_7));
  CLKINVX1 g1190(.A (G117), .Y (n_0));
  CLKINVX1 g1186(.A (G13), .Y (n_26));
  CLKINVX1 g1187(.A (G14), .Y (n_1));
  CLKINVX1 g1189(.A (G11), .Y (n_8));
  CLKINVX2 g1188(.A (G12), .Y (n_6));
  AO21X1 g2(.A0 (G66), .A1 (n_42), .B0 (n_46), .Y (n_54));
endmodule

