
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 19 2025 02:32:41 EST (Feb 19 2025 07:32:41 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, enable, count, SE);
  input clk, reset, enable, SE;
  output [3:0] count;
  wire clk, reset, enable, SE;
  wire [3:0] count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  SDFFRHQX1 \count_reg[3] (.RN (n_14), .CK (clk), .D (n_13), .SI
       (count[3]), .SE (1'b0), .Q (count[3]));
  SDFFRHQX1 \count_reg[2] (.RN (n_14), .CK (clk), .D (n_10), .SI
       (count[2]), .SE (1'b0), .Q (count[2]));
  MX2X1 g81__2398(.A (n_11), .B (n_12), .S0 (enable), .Y (n_13));
  CLKXOR2X1 g84__5107(.A (n_11), .B (n_8), .Y (n_12));
  MX2X1 g83__6260(.A (n_7), .B (n_9), .S0 (enable), .Y (n_10));
  SDFFRHQX1 \count_reg[1] (.RN (n_14), .CK (clk), .D (n_6), .SI
       (count[1]), .SE (1'b0), .Q (count[1]));
  ADDHX1 g85__4319(.A (n_7), .B (n_4), .CO (n_8), .S (n_9));
  SDFFRHQX1 \count_reg[0] (.RN (n_14), .CK (clk), .D (n_2), .SI
       (count[0]), .SE (1'b0), .Q (count[0]));
  MX2X1 g87__8428(.A (n_3), .B (n_5), .S0 (enable), .Y (n_6));
  ADDHX1 g88__5526(.A (n_3), .B (n_0), .CO (n_4), .S (n_5));
  CLKXOR2X1 g90__6783(.A (enable), .B (n_1), .Y (n_2));
  BUFX2 g92(.A (n_0), .Y (n_1));
  BUFX2 g91(.A (count[3]), .Y (n_11));
  BUFX2 g93(.A (count[0]), .Y (n_0));
  BUFX2 g96(.A (count[2]), .Y (n_7));
  BUFX2 g95(.A (count[1]), .Y (n_3));
  INVXL g94(.A (reset), .Y (n_14));
endmodule

