
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 19 2025 02:32:50 EST (Feb 19 2025 07:32:50 UTC)

// Verification Directory fv/counter 

module counter(clk, reset, enable, count, SE);
  input clk, reset, enable, SE;
  output [3:0] count;
  wire clk, reset, enable, SE;
  wire [3:0] count;
  wire n_2, n_4, n_5, n_6, n_8, n_9, n_10, n_14;
  wire n_18, n_19;
  SDFFRHQX1 \count_reg[3] (.RN (n_14), .CK (clk), .D (n_19), .SI
       (count[3]), .SE (1'b0), .Q (count[3]));
  SDFFRHQX1 \count_reg[2] (.RN (n_14), .CK (clk), .D (n_10), .SI
       (count[2]), .SE (1'b0), .Q (count[2]));
  MX2X1 g83__6260(.A (count[2]), .B (n_9), .S0 (enable), .Y (n_10));
  SDFFRHQX1 \count_reg[1] (.RN (n_14), .CK (clk), .D (n_6), .SI
       (count[1]), .SE (1'b0), .Q (count[1]));
  ADDHX1 g85__4319(.A (count[2]), .B (n_4), .CO (n_8), .S (n_9));
  SDFFRHQX1 \count_reg[0] (.RN (n_14), .CK (clk), .D (n_2), .SI
       (count[0]), .SE (1'b0), .Q (count[0]));
  MX2X1 g87__8428(.A (count[1]), .B (n_5), .S0 (enable), .Y (n_6));
  ADDHX1 g88__5526(.A (count[1]), .B (count[0]), .CO (n_4), .S (n_5));
  CLKXOR2X1 g90__6783(.A (enable), .B (count[0]), .Y (n_2));
  INVXL g94(.A (reset), .Y (n_14));
  XNOR2X1 g2(.A (n_18), .B (count[3]), .Y (n_19));
  NAND2XL g3(.A (n_8), .B (enable), .Y (n_18));
endmodule

