
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 14 2025 16:24:29 IST (Feb 14 2025 10:54:29 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire UNCONNECTED, mc_rb_fuse_vld_q, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16;
  sky130_fd_sc_ms__dfrtp_1 \skew_addr_cntr_reg[4] (.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D (n_16), .Q
       (skew_addr_cntr_o[4]));
  sky130_fd_sc_ms__nor2_1 g481__2398(.A (n_13), .B (n_15), .Y (n_16));
  sky130_fd_sc_ms__dfrtp_1 \skew_addr_cntr_reg[3] (.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D (n_14), .Q
       (skew_addr_cntr_o[3]));
  sky130_fd_sc_ms__xnor2_1 g483__5107(.A (n_11), .B
       (skew_addr_cntr_o[4]), .Y (n_15));
  sky130_fd_sc_ms__nor2b_1 g486__6260(.A (n_13), .B_N (n_12), .Y
       (n_14));
  sky130_fd_sc_ms__ha_1 g488__4319(.A (skew_addr_cntr_o[3]), .B (n_6),
       .COUT (n_11), .SUM (n_12));
  sky130_fd_sc_ms__dfrtp_1 \skew_addr_cntr_reg[1] (.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D (n_10), .Q
       (skew_addr_cntr_o[1]));
  sky130_fd_sc_ms__dfrtp_1 \skew_addr_cntr_reg[2] (.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D (n_9), .Q
       (skew_addr_cntr_o[2]));
  sky130_fd_sc_ms__dfrtp_1 \skew_addr_cntr_reg[0] (.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D (n_8), .Q
       (skew_addr_cntr_o[0]));
  sky130_fd_sc_ms__nor2b_1 g489__8428(.A (n_13), .B_N (n_4), .Y (n_10));
  sky130_fd_sc_ms__nor2b_1 g490__5526(.A (n_13), .B_N (n_7), .Y (n_9));
  sky130_fd_sc_ms__nor2_1 g491__6783(.A (skew_addr_cntr_o[0]), .B
       (n_13), .Y (n_8));
  sky130_fd_sc_ms__ha_1 g494__3680(.A (skew_addr_cntr_o[2]), .B (n_3),
       .COUT (n_6), .SUM (n_7));
  sky130_fd_sc_ms__nor2_1 g492__1617(.A (n_2), .B (n_5), .Y (n_13));
  sky130_fd_sc_ms__o22ai_1 g493__2802(.A1 (skew_addr_cntr_o[4]), .A2
       (n_1), .B1 (mc_rb_ef1_svld_i), .B2 (mc_rb_fuse_vld_q), .Y (n_5));
  sky130_fd_sc_ms__ha_1 g496__1705(.A (skew_addr_cntr_o[1]), .B
       (skew_addr_cntr_o[0]), .COUT (n_3), .SUM (n_4));
  sky130_fd_sc_ms__nor3_1 g497__5122(.A (skew_addr_cntr_o[3]), .B
       (skew_addr_cntr_o[2]), .C (n_0), .Y (n_2));
  sky130_fd_sc_ms__nor4_1 g495__8246(.A (skew_addr_cntr_o[3]), .B
       (skew_addr_cntr_o[0]), .C (skew_addr_cntr_o[2]), .D
       (skew_addr_cntr_o[1]), .Y (n_1));
  sky130_fd_sc_ms__dfrbp_1 mc_rb_fuse_vld_q_reg(.RESET_B
       (gctl_rclk_orst_n_i), .CLK (mc_rb_ef1_sclk_i), .D
       (mc_rb_fuse_vld_i), .Q (UNCONNECTED), .Q_N (mc_rb_fuse_vld_q));
  sky130_fd_sc_ms__inv_1 g499(.A (skew_addr_cntr_o[4]), .Y (n_0));
endmodule

