
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Feb 14 2025 16:24:20 IST (Feb 14 2025 10:54:20 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire mc_rb_fuse_vld_q, n_19, n_79, n_136, n_139, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_158, n_159, n_160;
  wire n_161, n_165, n_166, n_167, n_168, n_169, n_170, n_171;
  wire n_172, n_173, n_174, n_175, n_176, n_177;
  not g4 (n_19, gctl_rclk_orst_n_i);
  nand g194 (n_139, skew_addr_cntr_o[1], skew_addr_cntr_o[0]);
  or g206 (n_136, n_139, wc);
  not gc (wc, skew_addr_cntr_o[2]);
  or g224 (n_145, wc0, n_136);
  not gc0 (wc0, skew_addr_cntr_o[3]);
  or g229 (n_147, skew_addr_cntr_o[2], skew_addr_cntr_o[3]);
  or g232 (n_148, wc1, mc_rb_ef1_svld_i);
  not gc1 (wc1, mc_rb_fuse_vld_q);
  nand g256 (n_79, n_149, n_148);
  nand g257 (n_149, n_160, n_161);
  nand g258 (n_170, n_145, skew_addr_cntr_o[4]);
  or g259 (n_171, n_145, skew_addr_cntr_o[4]);
  nand g260 (n_146, n_170, n_171);
  or g261 (n_161, n_159, skew_addr_cntr_o[0]);
  or g262 (n_159, n_158, skew_addr_cntr_o[1]);
  nand g263 (n_172, skew_addr_cntr_o[3], n_136);
  or g264 (n_173, skew_addr_cntr_o[3], n_136);
  nand g265 (n_142, n_172, n_173);
  nand g266 (n_174, skew_addr_cntr_o[2], n_139);
  or g267 (n_175, skew_addr_cntr_o[2], n_139);
  nand g268 (n_144, n_174, n_175);
  nand g269 (n_160, n_147, skew_addr_cntr_o[4]);
  or g270 (n_158, n_147, skew_addr_cntr_o[4]);
  or g271 (n_176, wc2, skew_addr_cntr_o[1]);
  not gc2 (wc2, skew_addr_cntr_o[0]);
  or g272 (n_177, skew_addr_cntr_o[0], wc3);
  not gc3 (wc3, skew_addr_cntr_o[1]);
  nand g273 (n_143, n_176, n_177);
  and g274 (n_165, n_143, n_79);
  and g275 (n_166, n_79, wc4);
  not gc4 (wc4, skew_addr_cntr_o[0]);
  and g276 (n_167, n_142, n_79);
  and g277 (n_168, n_144, n_79);
  and g278 (n_169, n_146, n_79);
  CDN_flop mc_rb_fuse_vld_q_reg(.clk (mc_rb_ef1_sclk_i), .d
       (mc_rb_fuse_vld_i), .sena (1'b1), .aclr (n_19), .apre (1'b0),
       .srl (1'b0), .srd (1'b0), .q (mc_rb_fuse_vld_q));
  CDN_flop \skew_addr_cntr_reg[0] (.clk (mc_rb_ef1_sclk_i), .d (n_166),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[0]));
  CDN_flop \skew_addr_cntr_reg[1] (.clk (mc_rb_ef1_sclk_i), .d (n_165),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[1]));
  CDN_flop \skew_addr_cntr_reg[2] (.clk (mc_rb_ef1_sclk_i), .d (n_168),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[2]));
  CDN_flop \skew_addr_cntr_reg[3] (.clk (mc_rb_ef1_sclk_i), .d (n_167),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[3]));
  CDN_flop \skew_addr_cntr_reg[4] (.clk (mc_rb_ef1_sclk_i), .d (n_169),
       .sena (1'b1), .aclr (n_19), .apre (1'b0), .srl (1'b0), .srd
       (1'b0), .q (skew_addr_cntr_o[4]));
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
